<?php

namespace Proxies\__CG__\MisCupones\CuponBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cupon extends \MisCupones\CuponBundle\Entity\Cupon implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'titulo', 'descripcion', 'precio', 'precio_anterior', 'ruta_imagen', 'fecha_fin_venta', 'fecha_fin_canjeo', 'publicado', 'cuponesEstablecimientos', 'compras');
        }

        return array('__isInitialized__', 'id', 'titulo', 'descripcion', 'precio', 'precio_anterior', 'ruta_imagen', 'fecha_fin_venta', 'fecha_fin_canjeo', 'publicado', 'cuponesEstablecimientos', 'compras');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cupon $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', array($precio));

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', array());

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioAnterior($precioAnterior)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioAnterior', array($precioAnterior));

        return parent::setPrecioAnterior($precioAnterior);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioAnterior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioAnterior', array());

        return parent::getPrecioAnterior();
    }

    /**
     * {@inheritDoc}
     */
    public function setRutaImagen($rutaImagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutaImagen', array($rutaImagen));

        return parent::setRutaImagen($rutaImagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaImagen', array());

        return parent::getRutaImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFinVenta($fechaFinVenta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFinVenta', array($fechaFinVenta));

        return parent::setFechaFinVenta($fechaFinVenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinVenta', array());

        return parent::getFechaFinVenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFinCanjeo($fechaFinCanjeo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFinCanjeo', array($fechaFinCanjeo));

        return parent::setFechaFinCanjeo($fechaFinCanjeo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinCanjeo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinCanjeo', array());

        return parent::getFechaFinCanjeo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicado($publicado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicado', array($publicado));

        return parent::setPublicado($publicado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicado', array());

        return parent::getPublicado();
    }

    /**
     * {@inheritDoc}
     */
    public function addCuponesEstablecimiento(\MisCupones\CuponBundle\Entity\CuponEstablecimiento $cuponesEstablecimientos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCuponesEstablecimiento', array($cuponesEstablecimientos));

        return parent::addCuponesEstablecimiento($cuponesEstablecimientos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCuponesEstablecimiento(\MisCupones\CuponBundle\Entity\CuponEstablecimiento $cuponesEstablecimientos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCuponesEstablecimiento', array($cuponesEstablecimientos));

        return parent::removeCuponesEstablecimiento($cuponesEstablecimientos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuponesEstablecimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuponesEstablecimientos', array());

        return parent::getCuponesEstablecimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function addCompra(\MisCupones\ComprasBundle\Entity\Compra $compras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCompra', array($compras));

        return parent::addCompra($compras);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCompra(\MisCupones\ComprasBundle\Entity\Compra $compras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCompra', array($compras));

        return parent::removeCompra($compras);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompras', array());

        return parent::getCompras();
    }

}
