compras:
    resource: "@ComprasBundle/Resources/config/routing.yml"
    prefix:   /

usuarios:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   /

establecimientos:
    resource: "@EstablecimientosBundle/Resources/config/routing.yml"
    prefix:   /

cupon:
    resource: "@CuponBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
