# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #in_memory:
        #    memory: ~

        usuarios:
            entity: { class: MisCupones\UsuariosBundle\Entity\Usuario, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/*
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: usuario_login
                check_path: usuario_login_check

            logout:
                path:   /logout
                target: /

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/usuario/*, roles: [ROLE_USUARIO, ROLE_UESTABLECIMIENTO] }
        - { path: ^/estadisticas, roles: ROLE_UESTABLECIMIENTO }

    encoders:
        MisCupones\UsuariosBundle\Entity\Usuario: plaintext
