<?php

namespace Proxies\__CG__\MisCupones\EstablecimientosBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Establecimiento extends \MisCupones\EstablecimientosBundle\Entity\Establecimiento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'titulo', 'descripcion', 'direccion', 'provincia', 'municipio', 'codigo_postal', 'latitud', 'longitud', 'telefono', 'email', 'web', 'cuponesEstablecimientos', 'compras', 'usuariosEstablecimientos');
        }

        return array('__isInitialized__', 'id', 'titulo', 'descripcion', 'direccion', 'provincia', 'municipio', 'codigo_postal', 'latitud', 'longitud', 'telefono', 'email', 'web', 'cuponesEstablecimientos', 'compras', 'usuariosEstablecimientos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Establecimiento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia($provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', array($provincia));

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', array());

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio($municipio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', array($municipio));

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', array());

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPostal($codigoPostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPostal', array($codigoPostal));

        return parent::setCodigoPostal($codigoPostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPostal', array());

        return parent::getCodigoPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitud($latitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitud', array($latitud));

        return parent::setLatitud($latitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitud', array());

        return parent::getLatitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitud($longitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitud', array($longitud));

        return parent::setLongitud($longitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitud', array());

        return parent::getLongitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeb($web)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeb', array($web));

        return parent::setWeb($web);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeb', array());

        return parent::getWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function addCuponesEstablecimiento(\MisCupones\CuponBundle\Entity\CuponEstablecimiento $cuponesEstablecimientos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCuponesEstablecimiento', array($cuponesEstablecimientos));

        return parent::addCuponesEstablecimiento($cuponesEstablecimientos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCuponesEstablecimiento(\MisCupones\CuponBundle\Entity\CuponEstablecimiento $cuponesEstablecimientos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCuponesEstablecimiento', array($cuponesEstablecimientos));

        return parent::removeCuponesEstablecimiento($cuponesEstablecimientos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuponesEstablecimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuponesEstablecimientos', array());

        return parent::getCuponesEstablecimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function addCompra(\MisCupones\ComprasBundle\Entity\Compra $compras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCompra', array($compras));

        return parent::addCompra($compras);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCompra(\MisCupones\ComprasBundle\Entity\Compra $compras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCompra', array($compras));

        return parent::removeCompra($compras);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompras', array());

        return parent::getCompras();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuariosEstablecimiento(\MisCupones\EstablecimientosBundle\Entity\usuarioEstablecimiento $usuariosEstablecimientos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuariosEstablecimiento', array($usuariosEstablecimientos));

        return parent::addUsuariosEstablecimiento($usuariosEstablecimientos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuariosEstablecimiento(\MisCupones\EstablecimientosBundle\Entity\usuarioEstablecimiento $usuariosEstablecimientos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuariosEstablecimiento', array($usuariosEstablecimientos));

        return parent::removeUsuariosEstablecimiento($usuariosEstablecimientos);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariosEstablecimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariosEstablecimientos', array());

        return parent::getUsuariosEstablecimientos();
    }

}
